### ISSUE TITLE
room recording is not working 

### ISSUE THREAD

**Issue by marwa-benhassine** [riadvice/hivelvet#773] opened 2023-06-27 11:28 UTC
**Describe the bug**

 Rename button not working in room recording
publish  button not working in room recording
delete  button not working in room recording
replay  button not working in room recording

**To Reproduce**

1. Go to the rooms page .
2. Go to Room recordings
3. Click the  Rename  button

**Expected behavior**

All buttons in the Room recordings  must be working 

**Screenshots**

![image](https://github.com/riadvice/bbbeasy/assets/108723664/86365c58-c4fb-4150-ae7c-fbb36ef39a3c)

**Desktop (please complete the following information):**

OS: Windows

Browser: Chrome/Edge/Firefox

**Comment by GhaziTriki** [comment] 2023-07-24 09:28
Duplicate of #29

**Closed as completed by GhaziTriki** 2023-07-24 09:28 UTC
Labels: type: bug, status: duplicate, component: recordings, component: rooms
