### ISSUE TITLE
An error message is displayed for labels when the role name is renamed

### ISSUE THREAD

**Issue by marwa-benhassine** [riadvice/hivelvet#910] opened 2023-09-06 13:36 UTC
**Describe the bug**

An error message is displayed for labels when the role name is renamed

**To Reproduce**

1. Go to the role  page
2. Click on the Edit button
3. change the role name 

**Expected behavior**

An error message should appear when creating a role name: 'The role name cannot be longer than 64 characters', not a label name error message on the role page.

**Screenshots**

![rename name ](https://github.com/riadvice/bbbeasy/assets/108723664/302c0606-c313-491a-8c1b-583c587f5b1f)

**Desktop (please complete the following information):**

OS: Windows

Browser: Chrome/Edge/Firefox

**Comment by GhaziTriki** [comment] 2024-11-27 08:02
@marwa-benhassine The error looks legitimate. Can you retest?

**Comment by marwa-benhassine** [comment] 2024-11-27 08:33
https://github.com/riadvice/bbbeasy/issues/910#issuecomment-2503172718
Yes of course, we should replace "**Label** name cannot be longer than **32** characters" with "**Role** name cannot be longer than **64** characters" in the error message.

**Comment by GhaziTriki** [comment] 2024-11-27 10:52
Duplicate of #909, Same component.

**Closed as completed by GhaziTriki** 2024-11-27 10:52 UTC
Labels: type: bug, status: duplicate, component: roles, status: verify
